# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1018c7775063a51b78d64e645444776aa9b2a253154f5cbed1d13ab38674e3cb05092813f9813d5055b0752fb1671da57f0a8e6929a52cf4e073110c44d3c597

test:
  secret_key_base: 1984f16df6047d1308f76685789a49d6fd1fde18c818e80f20c4f8bee4ee438426ca7b56f1b1f5f07c6c4d0c43cb376043771c73b1c7104273cf02f367465010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
